<a href="https://colab.research.google.com/github/sangho-shane/JOB/blob/master/homework8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TEST

In [10]:
import torch
import numpy as np
data = [[1,2,3],[1,2,3,]]
x_data = torch.tensor(data)
print(x_data)

np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2, 3],
        [1, 2, 3]])
[[1 2 3]
 [1 2 3]]
tensor([[1, 2, 3],
        [1, 2, 3]])


In [28]:
import torch
import numpy as np
shape = (3,5)
x_rand = torch.rand(shape)
print(x_rand)
x_ones = torch.ones(shape)
print(x_ones)
x_zeros = torch.zeros(shape)
print(x_zeros)
print(x_rand[0])
print(x_rand[0:2,0:2])
x_rand[:1] = 0
print(x_rand)
x_rand[:,2]= 2
print(x_rand)
print(torch.cat([x_ones,x_zeros],dim=1))
print(x_rand)
print(torch.transpose(x_rand,0,1))
print(x_ones.T)
print('one',x_ones)
print('zero',x_zeros)
print('one * zero',x_ones * x_zeros)
print('one @ zero',x_ones.T @ x_zeros)
print('x_ones.sum()',x_ones.sum())


tensor([[0.6812, 0.2714, 0.4307, 0.9182, 0.4111],
        [0.1301, 0.6241, 0.7997, 0.6680, 0.3181],
        [0.2893, 0.2647, 0.8237, 0.9929, 0.0228]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([0.6812, 0.2714, 0.4307, 0.9182, 0.4111])
tensor([[0.6812, 0.2714],
        [0.1301, 0.6241]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1301, 0.6241, 0.7997, 0.6680, 0.3181],
        [0.2893, 0.2647, 0.8237, 0.9929, 0.0228]])
tensor([[0.0000, 0.0000, 2.0000, 0.0000, 0.0000],
        [0.1301, 0.6241, 2.0000, 0.6680, 0.3181],
        [0.2893, 0.2647, 2.0000, 0.9929, 0.0228]])
tensor([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])
tensor([[0.0000, 0.0000, 2.0000, 0.0000, 0.0000],
        [0.1301, 0.6241, 2.0000, 0.6680, 0.3181],
        [0.2

# 새 섹션

In [42]:
#homework 7
# Songeui Kim. 2021/10/24
# Word matching

import math
import random

# read data
filename = "one_654.txt"

print(filename)
file = open(filename, "r",encoding="utf8")
file.name
data = []

for i in file:
    data.append(i.split())
file.close()



NFIRST = 21
NLAST = 28
NMIDDLE = 21


PFIRST = 18 + 1
PMIDDLE = 21
PLAST = 7 + 1

HanList = \
[['ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅃ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅉ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'],\
['ㅏ', 'ㅐ', 'ㅑ', 'ㅒ', 'ㅓ', 'ㅔ', 'ㅕ', 'ㅖ', 'ㅗ', 'ㅘ', 'ㅙ', 'ㅚ', 'ㅛ', 'ㅜ', 'ㅝ', 'ㅞ', 'ㅟ', 'ㅠ', 'ㅡ', 'ㅢ', 'ㅣ'],\
[' ', 'ㄱ', 'ㄲ', 'ㄳ', 'ㄴ', 'ㄵ', 'ㄶ', 'ㄷ', 'ㄹ', 'ㄺ', 'ㄻ', 'ㄼ', 'ㄽ', 'ㄾ', 'ㄿ', 'ㅀ', 'ㅁ', 'ㅂ', 'ㅄ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ']\
]

HanphomeList = [
['ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅃ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅉ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'], \
['ㅏ', 'ㅐ', 'ㅑ', 'ㅒ', 'ㅓ', 'ㅔ', 'ㅕ', 'ㅖ', 'ㅗ', 'ㅘ', 'ㅙ', 'ㅚ', 'ㅛ', 'ㅜ', 'ㅝ', 'ㅞ', 'ㅟ', 'ㅠ', 'ㅡ', 'ㅢ', 'ㅣ'], \
['$','ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅇ'] \
]

Hanmatrix = [[len(HanList[0]),len(HanList[1]),len(HanList[2])],[len(HanphomeList[0]),len(HanphomeList[1]),len(HanphomeList[2])]]


def text_to_int_han(text): #한 글자로 초성 중성 종성 숫자찾기
    uncoden = ord(text)
    relpos = uncoden - int('0xAC00', 16) # (10588)
    first = relpos // (NMIDDLE * NLAST) # (10588//(21*28)= 18, 즉 HanList[0][18] = ‘ㅎ’)
    relpos = relpos % (NMIDDLE * NLAST) # (10588%(21*28) = 4)
    middle = relpos // NLAST # (4//28 = 0, 즉, HanList[1][0]=‘ㅏ’)
    last = relpos % NLAST # (4%28 = 4, Han[2][4] = ‘ㄴ’)
    return [first,middle,last]
#return [onehot(NFIRST,first), onehot(NMIDDLE,middle), onehot(NLAST,last)]

def int_to_text_phome(a,b,c): #자음+모음+자음 숫자로 텍스트 자음+모음+자음 찾기 - hanphomelist
    a = HanphomeList[0][a]
    b = HanphomeList[1][b]
    c = HanphomeList[2][c]
    #print(a,b,c)
    return str_to_text_han(a,b,c)

def str_to_text_han(a,b,c): #자음+모음+자음 텍스트로 글자만들기 - hanlist
    a = HanList[0].index(a, 0, NFIRST)
    b = HanList[1].index(b, 0, NMIDDLE)
    c = HanList[2].index(c.replace('$',' '), 0, NLAST)
    #print(a, b, c)
    return int_to_text_han(a,b,c)

def int_to_text_han(a, b, c): #초성 중성 종성 숫자로 글자만들기 - hanlist
    relpos = a * 588 + 28 * b + c
    return chr(relpos + int('0xAC00', 16))

def onehot(total,choice):
    a = [0 for g in range(total)]
    a[choice] = 1
    return a

def activate(a):
    return max(a, 0)
#return 1 / (1 + math.exp(-1 * a))


def derivative(a):
    if a > 0 :
        return 1
    else :
        return 0
#return a * (1 - a)


def activate2(a):
    return 1 / (1 + math.exp(-1 * a))


def derivative2(a):
    return a * (1 - a)

def dehot(a):
    return a.index(max(a),0,len(a))


datas = []
for i, j, k, l, m in data:
    data2 = []
    data3 = []
    print(k,l,m)
    k = HanphomeList[0].index(k, 0, PFIRST)
    l = HanphomeList[1].index(l, 0, PMIDDLE)
    m = HanphomeList[2].index(m, 0, PLAST)
    data2.append(k)
    data2.append(l)
    data2.append(m)
    data3 = [text_to_int_han(i)]
    data3.append(data2)
    data3.append([int(j)])
    datas.append(data3)

NI = Hanmatrix[0] # N of inputs
NH = 50
NO = Hanmatrix[1]
N = len(datas[0])

NEPOCH = 100
LR = 0.1/N # learning rate 0.4/4




# weight initialize
woh = [[[random.uniform(-0.2, 0.2) for j in range(NH)] for g in range(NO[i])] for i in range(3)] # 3 * NO * NH
whi = [[[random.uniform(-0.2, 0.2) for g in range(NI[i])] for j in range(NH)] for i in range(3)] # 3 * NH * NI

o_bias = [[random.random() for i in range(NO[k])] for k in range(3)] # 3 * NO
h_bias = [[random.random() for i in range(NH)] for k in range(3)] # 3 * NH

ao = [[0.0 for i in range(NO[j])] for j in range(3)]
ah = [[0.0 for i in range(NH)] for j in range(3)]
do = [[0.0 for i in range(NO[j])] for j in range(3)]
dh = [[0.0 for i in range(NH)] for j in range(3)]

#training

print("Start Training!")
print("Trainning...( 0 / ", (NEPOCH), " ) -- hidden layer:",NH)
for x in range(NEPOCH):

    # initialize
    dwoh = [[[0.0 for j in range(NH)] for g in range(NO[i])] for i in range(3)] # 3 * NO * NH
    dwhi = [[[0.0 for g in range(NI[i])] for j in range(NH)] for i in range(3)] # 3 * NH * NI
    do_bias = [[0.0 for i in range(NO[k])] for k in range(3)]
    dh_bias = [[0.0 for i in range(NH)] for k in range(3)]

    for item in datas:
        inputs = item[0]
        label = item[1]
        logs = item[2]
        if 0.186022636658652*math.log(logs[0]+2) > random.uniform(0, 1):
            for i in range(len(Hanmatrix[0])):
                inputs2 = onehot(NI[i], inputs[i])
                label2 = onehot(NO[i], label[i])
                for j in range(NH):
                    out = 0.0
                    for k in range(NI[i]):
                        out = out + whi[i][j][k] * inputs2[k]
                    out = out + h_bias[i][j]
                    #ao[j] = 1 / (1 + math.exp(-1 * out))
                    #if out > 0:
                    # ah[j]=out
                    #else:
                    # ah[j]=out*0.01
                    ah[i][j] = activate(out)

                for j in range(NO[i]):
                    out = 0.0
                    for k in range(NH):
                        out = out + woh[i][j][k] * ah[i][k]
                    out = out + o_bias[i][j]
                    ao[i][j] = activate2(out)
                    #ao[i][j] = out
                for j in range(NO[i]):
                    ao[i][j] = ao[i][j] / sum(ao[i])

                ## backward
                for j in range(NO[i]):
                    do[i][j] = (label2[j] - ao[i][j]) * derivative2(ao[i][j])
                    do_bias[i][j] = do_bias[i][j] + LR * do[i][j]
                    for k in range(NH):
                        dwoh[i][j][k] = dwoh[i][j][k] + LR * do[i][j] * ah[i][k]

                for j in range(NH):
                    total = 0.0
                    for k in range(NO[i]):
                        total = total + do[i][k] * woh[i][k][j]
                    dh[i][j] = total * derivative(ah[i][j])
                    dh_bias[i][j] = dh_bias[i][j] + LR * dh[i][j]
                for j in range(NH):
                    for k in range(NI[i]):
                        dwhi[i][j][k] = dwhi[i][j][k] + LR * dh[i][j] * inputs2[k]

    # update weight
    for h in range(3):
        for i in range(NH):
            h_bias[h][i] = h_bias[h][i] + (1 / N) * dh_bias[h][i]
            for j in range(NI[h]):
                whi[h][i][j] = whi[h][i][j] + (1 / N) * dwhi[h][i][j]
        for i in range(NO[h]):
            o_bias[h][i] = o_bias[h][i] + (1 / N) * do_bias[h][i]
            for j in range(NH):
                woh[h][i][j] = woh[h][i][j] + (1 / N) * dwoh[h][i][j]
    print("Trainning...(", (x+1), '/', (NEPOCH), ")")

#prediction
print("----Test----")
def predicts(a,b):
    inserts = text_to_int_han(a)
    for i in range(len(Hanmatrix[0])):
        inputs2 = onehot(NI[i], inserts[i])
        for j in range(NH):
            out = 0.0
            for k in range(NI[i]):
                out = out + whi[i][j][k] * inputs2[k]
            out = out + h_bias[i][j]
            ah[i][j] = activate(out)

        for j in range(NO[i]):
            out = 0.0
            for k in range(NH):
                out = out + woh[i][j][k] * ah[i][k]
            out = out + o_bias[i][j]
            ao[i][j] = activate2(out)
        for j in range(NO[i]):
            ao[i][j] = ao[i][j] / sum(ao[i])

    inputing = int_to_text_han(inserts[0], inserts[1], inserts[2])
    outing = int_to_text_phome(int(round(dehot(ao[0]),0)),int(round(dehot(ao[1]),0)),int(round(dehot(ao[2]),0)))
    print("input: ",inputing,"(",inserts[0], inserts[1], inserts[2],"), predict: ",outing,"(",int(round(dehot(ao[0]),0)),int(round(dehot(ao[1]),0)),int(round(dehot(ao[2]),0)),") label: ",b)


for item in datas:
    inputs = item[0]
    label = item[1]
    predicts(int_to_text_han(inputs[0],inputs[1],inputs[2]),int_to_text_phome(label[0],label[1],label[2]))



# print "After training, weight:", weight

one_654.txt


UnicodeDecodeError: ignored